app:
  home: AUTH_SERVER_HOME
server:
  port: 8080

spring:
  datasource:
    ###### PostgreSQL Configuration #######
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth_server1
    username: mdzahidraza
    password: zahid

  jpa:
    show-sql: false
    format-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  enabled: false
  change-log: 'classpath:/db/changelog-master.xml'